#!/usr/bin/env python3
"""Generate the site's reference pages and the examples gallery from website/data and examples/.

    python3 website/scripts/gen_reference.py              # (re)write the generated pages
    python3 website/scripts/gen_reference.py --check      # exit 1 if a committed page is stale
    python3 website/scripts/gen_reference.py --check --fresh DIR
                                                          # also compare website/data with a fresh dump in DIR
                                                          # (dump_data.py --out DIR), as the test-suite does

Inputs (never hand-edit the outputs; change these instead):
  website/data/{tools,components,wander,cli,capi}.json   live engine data (dump_data.py)
  website/data/examples.json                             curated notes per example project
  examples/*/game.json, examples/*/scenes/*.sky.json      the projects themselves

Outputs: website/docs/reference/** and website/docs/examples/index.md. Standard library only.
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from collections import Counter, OrderedDict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SITE = ROOT / "website"
DATA = SITE / "data"
DOCS = SITE / "docs"
BANNER = "<!-- Generated by website/scripts/gen_reference.py from website/data. Do not edit: regenerate. -->\n"
REPO = "https://github.com/amirhossein-razlighi/Skywalker/blob/main/"

# ---------------------------------------------------------------------------------------------------------------
# Tool categories: page order, titles and a short human introduction (the tool list itself comes from the data).

CATEGORIES = OrderedDict([
    ("scene", ("Scene", "Orient yourself, query and save scenes, and batch many edits into one undo step.")),
    ("entity", ("Entity", "Create, read, change, move, duplicate and delete entities; read component schemas.")),
    ("history", ("History", "Undo, redo and the attributed edit history.")),
    ("view", ("View", "See the scene: captures with entity boxes, debug views, multi-view sheets, selection and the editor camera.")),
    ("render", ("Render", "Environment, effects, hair, shaders, render layers, impostors, benchmarks and the movie renderer.")),
    ("world", ("World", "Terrain, foliage, water queries and spatial placement on real geometry.")),
    ("asset", ("Asset", "The asset database, import and download, materials, textures, prefabs, audio generation and previews.")),
    ("wander", ("Wander", "Write, check, test, graph and inspect Wander behaviors.")),
    ("code", ("Code", "Native code: ahead-of-time compiled behaviors and C++ modules (trusted local code; clients ask first).")),
    ("sim", ("Simulation", "Play, pause, step and stop; inject input; trace and inspect what runs.")),
    ("physics", ("Physics", "Rigid bodies, characters, queries, settling and navigation meshes.")),
    ("animation", ("Animation", "Skeletal animation, controllers, IK, bone attachments and cinematic sequences.")),
    ("ui", ("UI", "Build, style, inspect and drive user interfaces.")),
    ("dialogue", ("Dialogue", "Lint, preview and control branching dialogue.")),
    ("studio", ("Studio", "The multi-agent studio: roster, board, feedback, decisions, loops, messages and playtests.")),
    ("dcc", ("DCC", "Design-app bridge: run scripts in Blender (and other apps), convert, generate and live sessions.")),
    ("files", ("Files", "Project settings, packaging the game as an app, running it in the real player, and the legal notices.")),
    ("network", ("Network", "Licensed downloads from the web, recorded with provenance and credits.")),
    ("tools", ("Custom tools", "Define, test, inspect, approve and manage the project's own tools (Wander, composite and hosted).")),
    ("agent", ("Agent layer", "The event log and hosted tools that external agent processes (such as the Python agent layer) use.")),
])

COMPONENT_GROUPS = OrderedDict([
    ("core", ("Core", "Every scene is built from these: placement, surfaces, lights, reflection probes, cameras, process modes and the "
              "scene-wide environment.", ["transform", "mesh", "light", "reflection_probe", "camera", "process", "environment"])),
    ("world", ("World and effects", "Large-scale world building and simulated effects.",
               ["terrain", "foliage", "water", "particles", "fluid", "groom"])),
    ("2d-ui", ("2D, text and UI", "Sprites, tilemaps, 2D lights and cameras, world text, UI canvases and dialogue.",
               ["sprite", "sprite_anim", "tilemap", "light2d", "particles2d", "parallax", "camera2d", "text", "ui_canvas", "ui",
                "dialogue"])),
    ("audio", ("Audio", "Spatial sound sources and the listener.", ["audio", "listener"])),
    ("physics", ("Physics and navigation", "Rigid bodies, colliders, characters, joints, vehicles, world settings and navigation.",
                 ["body", "collider", "character", "joint", "vehicle", "chase_camera", "physics_world", "navmesh", "nav_agent"])),
    ("animation", ("Animation", "Animators, character IK (foot planting, hand targets, turn in place), bone attachments, IK "
                   "effectors and sequence players.", ["animator", "characterIk", "attach", "ik", "sequencer"])),
])

# Example values for synthesized tool examples (only used when a tool's description has no "Example: {...}").
SAMPLE_STRINGS = {"entity": "Crate", "name": "Crate", "path": "scenes/main.sky.json", "preset": None, "agent": "nimbus",
                  "loop": "playtest_fix_verify", "query": "tree", "source": "on tick\n  rotate self by (0, 90 * dt, 0)\nend",
                  "text": "Hello", "title": "Fix the canyon jump", "id": "T-1", "message": "Ready for review",
                  "url": "https://example.com/model.glb", "license": "CC0-1.0", "folder": "art/props",
                  "image": "art/knight.png", "sequence": "Director", "camera": "Cam A", "target": "Hero",
                  "to": "Hero", "bone": "RightHand", "clip": "Walk", "script": "story/intro.dialogue",
                  "asset": "models/statue.glb", "file": "models/lantern.glb", "code": "print('hello')",
                  "recipe": "tower", "summary": "Players fall at the second gap", "element": "Play", "canvas": "HUD",
                  "template": "indie_trio", "layer": "0", "report": "Done", "goal": "Reach the gate"}


CURATED: dict[str, dict] = {}


def load(name: str):
    return json.loads((DATA / name).read_text())


def md_escape(text: str) -> str:
    return text.replace("|", "\\|").replace("\n", " ").replace("<", "&lt;").replace(">", "&gt;")


def slug(text: str) -> str:
    return re.sub(r"[^a-z0-9_-]+", "-", text.lower()).strip("-")


def balanced_json(text: str, start: int) -> str | None:
    depth, i, in_str = 0, start, False
    while i < len(text):
        c = text[i]
        if in_str:
            if c == "\\":
                i += 1
            elif c == '"':
                in_str = False
        elif c == '"':
            in_str = True
        elif c == "{":
            depth += 1
        elif c == "}":
            depth -= 1
            if depth == 0:
                return text[start:i + 1]
        i += 1
    return None


def described_example(desc: str):
    for m in re.finditer(r"(?i)\bexamples?\b[^{]{0,30}?(\{)", desc):
        raw = balanced_json(desc, m.start(1))
        if raw:
            try:
                value = json.loads(raw)
            except json.JSONDecodeError:
                continue
            if isinstance(value, dict):
                return value
    return None


def sample_value(name: str, schema: dict):
    if "enum" in schema and schema["enum"]:
        return schema["enum"][0]
    t = schema.get("type")
    if isinstance(t, list):
        t = t[0]
    if t == "string" or t is None:
        v = SAMPLE_STRINGS.get(name)
        return v if v is not None else name.replace("_", " ")
    if t == "integer":
        return int(max(schema.get("minimum", 1), 1))
    if t == "number":
        return max(schema.get("minimum", 1), 1)
    if t == "boolean":
        return True
    if t == "array":
        items = schema.get("items", {})
        return [sample_value(name.rstrip("s"), items if isinstance(items, dict) else {})]
    if t == "object":
        return {}
    return name


_MINED: dict | None = None


def mined_examples(tools: dict[str, dict]) -> dict[str, dict]:
    """Example calls written by the engine's authors in docs/*.md and the skills (validated against the schema)."""
    global _MINED
    if _MINED is not None:
        return _MINED
    import importlib.util
    spec = importlib.util.spec_from_file_location("check_skills", ROOT / "integrations" / "check_skills.py")
    sk = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(sk)
    found: dict[str, dict] = {}
    files = sorted((ROOT / "docs").glob("*.md")) + sorted((ROOT / "integrations" / "skills-src").rglob("*.md"))
    for f in files:
        text = f.read_text()
        for m in re.finditer(r"(?<![A-Za-z0-9_./-])([a-z][a-z0-9_]*)\s*\{", text):
            name = m.group(1)
            if name not in tools:
                continue
            end = sk.balanced(text, m.end() - 1)
            if end < 0:
                continue
            raw = text[m.end() - 1:end]
            if len(raw) > 400:
                continue
            try:
                args = json.loads(sk.js_to_json(sk.strip_comments(raw)))
            except json.JSONDecodeError:
                continue
            if not isinstance(args, dict) or not args:
                continue
            problems: list[str] = []
            sk.check_call(name, args, tools, "", problems)
            if problems or len(json.dumps(args)) > 360:
                continue
            best = found.get(name)
            if best is None or len(args) > len(best):
                found[name] = args
    _MINED = found
    return found


def example_args(tool: dict, tools: dict[str, dict] | None = None):
    found = described_example(tool["description"])
    if found is not None:
        return found, True
    curated = CURATED.get(tool["name"])
    if curated is not None:
        return curated.get("_args", curated), True
    if tools is not None:
        mined = mined_examples(tools).get(tool["name"])
        if mined is not None:
            return mined, True
    schema = tool["inputSchema"]
    props = schema.get("properties", {})
    return {k: sample_value(k, props.get(k, {})) for k in schema.get("required", [])}, False


def type_text(schema: dict) -> str:
    if not isinstance(schema, dict):
        return ""
    t = schema.get("type")
    if t is None:
        if "oneOf" in schema or "anyOf" in schema:
            return " \\| ".join(type_text(s) for s in schema.get("oneOf", schema.get("anyOf", [])))
        desc = schema.get("description", "")
        if "hex string" in desc or "#rrggbb" in desc:
            return "color"
        return "any"
    if isinstance(t, list):
        return " \\| ".join(t)
    if t == "array":
        items = schema.get("items")
        inner = type_text(items) if isinstance(items, dict) else ""
        n = schema.get("minItems")
        if n and n == schema.get("maxItems"):
            return f"{inner or 'any'}[{n}]"
        return f"{inner}[]" if inner else "array"
    return t


def constraints(schema: dict) -> str:
    parts = []
    if "enum" in schema:
        parts.append(" ".join(f"`{e}`" for e in schema["enum"]))
    lo, hi = schema.get("minimum"), schema.get("maximum")
    if lo is not None and hi is not None:
        parts.append(f"{fmt_num(lo)} .. {fmt_num(hi)}")
    elif lo is not None:
        parts.append(f"≥ {fmt_num(lo)}")
    elif hi is not None:
        parts.append(f"≤ {fmt_num(hi)}")
    if "default" in schema:
        parts.append(f"default `{json.dumps(schema['default'])}`")
    return "<br>".join(parts)


def fmt_num(v) -> str:
    return str(int(v)) if isinstance(v, float) and v.is_integer() else str(v)


def compact(value) -> str:
    return json.dumps(value, ensure_ascii=False, separators=(", ", ": "))


# ---------------------------------------------------------------------------------------------------------------
# Tools


def tools_by_category(tools: list[dict]):
    cats: dict[str, list[dict]] = OrderedDict((c, []) for c in CATEGORIES)
    for t in tools:
        cat = t.get("_meta", {}).get("skywalker/category", "misc")
        if cat not in cats:
            raise SystemExit(f"tool category '{cat}' ({t['name']}) has no page: add it to CATEGORIES in "
                             "website/scripts/gen_reference.py and to the Reference > Tools nav in website/mkdocs.yml")
        cats[cat].append(t)
    return cats


def badges(tool: dict) -> str:
    ann = tool.get("annotations", {})
    out = []
    if ann.get("readOnlyHint"):
        out.append('<span class="sky-badge sky-badge--ro" title="Never changes the scene">read-only</span>')
    else:
        out.append('<span class="sky-badge sky-badge--mut" title="Changes the project; undoable and attributed">mutating</span>')
    if ann.get("destructiveHint"):
        out.append('<span class="sky-badge" title="May remove or overwrite data">destructive</span>')
    if ann.get("openWorldHint"):
        out.append('<span class="sky-badge sky-badge--open" title="Reaches outside the engine (network or other programs); '
                   'clients ask the human first">open-world</span>')
    return " ".join(out)


def param_rows(schema: dict, prefix: str = "", depth: int = 0) -> list[str]:
    rows = []
    required = set(schema.get("required", []))
    for name, sub in schema.get("properties", {}).items():
        if not isinstance(sub, dict):
            continue
        req = "yes" if name in required else ""
        desc = md_escape(sub.get("description", ""))
        rows.append(f"| `{prefix}{name}` | {type_text(sub)} | {req} | {desc} | {constraints(sub)} |")
        if depth < 1 and sub.get("type") == "object" and sub.get("properties"):
            rows += param_rows(sub, f"{prefix}{name}.", depth + 1)
        items = sub.get("items")
        if depth < 1 and isinstance(items, dict) and items.get("properties"):
            rows += param_rows(items, f"{prefix}{name}[].", depth + 1)
    return rows


def tool_section(tool: dict) -> str:
    name = tool["name"]
    title = tool.get("title") or name
    lines = [f"### `{name}` {{ #{name} }}", "", f"**{md_escape(title)}** {badges(tool)}", "", tool["description"].strip(), ""]
    rows = param_rows(tool["inputSchema"])
    if rows:
        lines += ["| Argument | Type | Required | Description | Values |", "|---|---|---|---|---|", *rows, ""]
    else:
        lines += ["Takes no arguments.", ""]
    args, from_desc = example_args(tool, TOOLS_BY_NAME)
    call = compact(args)
    shell = call.replace("'", "'\\''")
    rpc = {"jsonrpc": "2.0", "id": 1, "method": "tools/call", "params": {"name": name, "arguments": args}}
    lines += [
        '=== "Tool call"', "", "    ```tool", f"    {name} {call}", "    ```", "",
        '=== "CLI"', "", "    ```bash", f"    skywalker call {name} '{shell}' --project my_game", "    ```", "",
        '=== "MCP request"', "", "    ```json", *("    " + l for l in json.dumps(rpc, indent=2, ensure_ascii=False).splitlines()),
        "    ```", "",
    ]
    if not from_desc and args:
        lines += ["<small>Minimal call with the required arguments; see the table for everything else.</small>", ""]
    note = CURATED.get(tool["name"], {}).get("_note")
    if note:
        lines += [f"<small>{note}</small>", ""]
    return "\n".join(lines)


TOOLS_BY_NAME: dict[str, dict] = {}


def gen_tools(tools_data: dict) -> dict[str, str]:
    tools = tools_data["tools"]
    TOOLS_BY_NAME.update({t["name"]: t for t in tools})
    cats = tools_by_category(tools)
    pages = {}
    total = len(tools)
    mutating = sum(1 for t in tools if not t.get("annotations", {}).get("readOnlyHint"))
    idx = [BANNER, "# Tools", "",
           f"Skywalker exposes **{total} tools** (engine {tools_data['version']}). The editor, its in-app agents, the CLI and "
           "every MCP client call the same tools with the same JSON arguments, so anything you read here works everywhere. "
           f"{mutating} tools change the project; every such change is undoable and attributed to whoever made it.", "",
           "Arguments are validated before a tool runs: unknown keys, wrong types and bad enum values fail with a "
           "*did you mean …?* hint. Each tool page shows the arguments, the annotations MCP clients use for approvals, "
           "and the same call as a tool call, a CLI command and a raw MCP request.", "",
           "| Category | Tools | What for |", "|---|---|---|"]
    for cat, (title, intro) in CATEGORIES.items():
        idx.append(f"| [{title}]({cat}.md) | {len(cats[cat])} | {intro} |")
    idx += ["", "## Every tool", "", "| Tool | Category | Summary |", "|---|---|---|"]
    for cat, (title, _) in CATEGORIES.items():
        for t in sorted(cats[cat], key=lambda t: t["name"]):
            first = re.split(r"(?<=[.!?])\s", t["description"].strip(), maxsplit=1)[0]
            idx.append(f"| [`{t['name']}`]({cat}.md#{t['name']}) | {title} | {md_escape(first)} |")
    pages["reference/tools/index.md"] = "\n".join(idx) + "\n"
    for cat, (title, intro) in CATEGORIES.items():
        body = [BANNER, f"# {title} tools", "", intro, "",
                f"{len(cats[cat])} tools in the `{cat}` category. Badges: **read-only** tools never change the project; "
                "**mutating** tools are undoable and attributed; **open-world** tools reach outside the engine and MCP "
                "clients ask before running them.", "",
                "| Tool | Summary |", "|---|---|"]
        for t in cats[cat]:
            first = re.split(r"(?<=[.!?])\s", t["description"].strip(), maxsplit=1)[0]
            body.append(f"| [`{t['name']}`](#{t['name']}) | {md_escape(first)} |")
        body.append("")
        for t in cats[cat]:
            body.append(tool_section(t))
        pages[f"reference/tools/{cat}.md"] = "\n".join(body)
    return pages


# ---------------------------------------------------------------------------------------------------------------
# Components


def component_section(name: str, schema: dict) -> str:
    lines = [f"## `{name}` {{ #{name} }}", "", schema.get("description", "").strip(), ""]
    props = schema.get("properties", {})
    if props:
        lines += ["| Field | Type | Description | Values |", "|---|---|---|---|"]
        for field, sub in props.items():
            lines.append(f"| `{field}` | {type_text(sub)} | {md_escape(sub.get('description', ''))} | {constraints(sub)} |")
        lines.append("")
    first = next(iter(props), None)
    if name == "environment":
        lines += ['=== "Tool call"', "", "    ```tool", f"    environment_update {compact({'preset': 'sunset'})}", "    ```",
                  "", '=== "Wander"', "", "    Environment fields are scene settings, edited with `environment_update` "
                  "(or keyed in sequences as `environment.<field>`).", ""]
    elif first:
        lines += ['=== "Tool call"', "", "    ```tool",
                  f"    entity_update {compact({'entity': 'Crate', 'components': {name: {}}})}", "    ```", "",
                  f'=== "Wander"', "", "    ```text", f"    self.{name}.{first}          -- read or write any field", "    ```", ""]
    return "\n".join(lines)


def gen_components(comps: dict) -> dict[str, str]:
    pages = {}
    placed = {c for _, _, members in COMPONENT_GROUPS.values() for c in members}
    missing = [c for c in comps if c not in placed]
    if missing:
        raise SystemExit(f"components without a reference page: {', '.join(missing)}: add them to COMPONENT_GROUPS in "
                         "website/scripts/gen_reference.py")
    idx = [BANNER, "# Components", "",
           f"Every component is a plain struct with a reflected field table. The same table drives JSON scene files, "
           f"the JSON Schema agents read (`component_schema`), the editor's property grid and Wander access "
           f"(`self.light.intensity`). There are **{len(comps) - (1 if 'environment' in comps else 0)} components** "
           "plus the scene-wide environment.", "",
           "Set them with `entity_create` / `entity_update` (component objects are merged field by field), from the "
           "editor's Details panel, or from Wander. Unknown fields fail with a *did you mean …?* hint.", "",
           "| Component | Group | Description |", "|---|---|---|"]
    for key, (title, intro, members) in COMPONENT_GROUPS.items():
        for c in members:
            if c in comps:
                idx.append(f"| [`{c}`]({key}.md#{c}) | {title} | {md_escape(comps[c].get('description', ''))} |")
    pages["reference/components/index.md"] = "\n".join(idx) + "\n"
    for key, (title, intro, members) in COMPONENT_GROUPS.items():
        body = [BANNER, f"# {title}", "", intro, ""]
        for c in members:
            if c in comps:
                body.append(component_section(c, comps[c]))
        pages[f"reference/components/{key}.md"] = "\n".join(body)
    return pages


# ---------------------------------------------------------------------------------------------------------------
# Wander builtins


def gen_wander(w: dict) -> dict[str, str]:
    guide = w["guide"]
    w = {"guide": guide, "categories": OrderedDict(
        (c, [e for e in es if "name" in e]) for c, es in w["categories"].items() if any("name" in e for e in es))}
    triggers = []
    m = re.search(r"SUBSYSTEM TRIGGERS\n(.*?)(?:\nMore:|\Z)", guide, re.S)
    if m:
        for line in m.group(1).splitlines():
            tm = re.match(r"\s*(on \w+) — (.*)", line)
            if tm:
                triggers.append((tm.group(1), tm.group(2)))
    count = sum(len(v) for v in w["categories"].values())
    out = [BANNER, "# Wander builtins", "",
           f"Every function a Wander script can call lives in one registry: name, typed parameters, return type, category, "
           f"documentation and an example. The compiler checks calls against it (arity, types, did-you-mean), and this page "
           f"is generated from it. **{count} builtins** in {len(w['categories'])} categories.", "",
           "Agents get the same information from `wander_reference` (the guide) and `wander_reference {topic}` "
           "(structured entries for a category or a function). For the language itself, read the "
           "[Wander manual](../manual/wander/index.md).", "",
           "| Category | Builtins |", "|---|---|"]
    for cat, entries in w["categories"].items():
        names = ", ".join(f"[`{e['name']}`](#{slug(cat)}-{slug(e['name'])})" for e in entries)
        out.append(f"| [{cat}](#{slug(cat)}) | {names} |")
    out.append("")
    if triggers:
        out += ["## Subsystem triggers", "", "Besides the core triggers (`on start`, `on tick`, `on event`, `on key`, "
                "`on click`, `on frame`, and `on enter` / `on exit` inside states), subsystems register these:", "",
                "| Trigger | Fires when |", "|---|---|"]
        out += [f"| `{t}` | {md_escape(d)} |" for t, d in triggers]
        out.append("")
    for cat, entries in w["categories"].items():
        out += [f"## {cat} {{ #{slug(cat)} }}", ""]
        for e in entries:
            out += [f"### `{e['name']}` {{ #{slug(cat)}-{slug(e['name'])} }}", "", "```text", e["signature"], "```", "",
                    e.get("doc", "").strip(), ""]
            params = e.get("params", [])
            if params:
                out += ["| Parameter | Type | |", "|---|---|---|"]
                for p in params:
                    out.append(f"| `{p['name']}` | {md_escape(p.get('type', 'any'))} | {'optional' if p.get('optional') else ''} |")
                out.append("")
            if e.get("returns"):
                out += [f"Returns: `{e['returns']}`", ""]
            if e.get("example"):
                out += ["```text", e["example"], "```", ""]
    out += ["## The guide agents read", "",
            "`wander_reference` without a topic returns this text: a compact language guide followed by the builtin list.",
            "", '??? note "wander_reference output"', "", "    ```text"]
    out += ["    " + l if l else "" for l in guide.rstrip().splitlines()]
    out += ["    ```", ""]
    return {"reference/wander.md": "\n".join(out)}


# ---------------------------------------------------------------------------------------------------------------
# CLI and C API


CLI_NOTES = OrderedDict([
    ("mcp", "Run the MCP server: on stdio with a headless engine, bridged to a running editor (`--attach`), or "
            "whichever is available (`--auto`, what agent configs use)."),
    ("serve", "Run a headless engine that serves the agent socket like the editor, so several clients (Python agents, "
              "`mcp --attach`, `call --attach`) share one engine."),
    ("setup", "Install the MCP entry, skills, subagents and commands for Claude Code, Codex, Gemini CLI or Cursor."),
    ("render", "Render a scene file to a PNG (supersampled with `--samples`; `--annotate` labels entities with their ids)."),
    ("run", "Simulate a scene deterministically for N ticks, print the logs, optionally render the last frame."),
    ("check", "Compile a `.wander` file exactly as the engine would and print diagnostics."),
    ("call", "Run one tool on a scene or project, or on the running editor with `--attach`."),
    ("tools", "List every tool, as text, Markdown or the JSON that MCP clients receive."),
    ("studio", "Inspect the studio (roster, board, feedback, loops) or run a loop headless with your API keys."),
    ("build", "Package a project as a standalone macOS app around the player."),
    ("movie", "Render a cinematic offline to H.264, HEVC, ProRes or PNG frames."),
    ("legal", "Print the Terms of Use, the Privacy Notice or the license embedded in the binary, or record acceptance "
              "for headless and CI use (`--accept`)."),
    ("version", "Print the engine version."),
])


def gen_cli(cli: dict) -> dict[str, str]:
    usage = cli["usage"].rstrip()
    out = [BANNER, "# Command line", "",
           "`skywalker` is the headless engine: MCP server, renderer, simulator, Wander compiler, tool runner, studio "
           "runner, packager and movie renderer in one binary (`build/<preset>/bin/skywalker`). The help texts below are "
           "captured from the binary itself.", "",
           "| Command | Purpose |", "|---|---|"]
    out += [f"| [`skywalker {c}`](#{c}) | {d} |" for c, d in CLI_NOTES.items()]
    out += ["", "## Usage", "", "```text", *usage.splitlines(), "```", ""]
    for c, d in CLI_NOTES.items():
        out += [f"## `skywalker {c}` {{ #{c} }}", "", d, ""]
        if c in cli["commands"]:
            out += ["```text", *cli["commands"][c].rstrip().splitlines(), "```", ""]
        else:
            lines = [l for l in usage.splitlines() if re.match(rf"\s*skywalker {c}\b", l)]
            if lines:
                out += ["```text", *lines, "```", ""]
    return {"reference/cli.md": "\n".join(out)}


def gen_capi(capi: dict) -> dict[str, str]:
    out = [BANNER, "# C API", "",
           "The engine's stable ABI is a small C header, "
           f"[`engine/capi/include/sky_api.h`]({REPO}engine/capi/include/sky_api.h). The SwiftUI editor is built on it, and "
           "any language with a C FFI (Swift, Python, Rust, C#, Zig, JavaScript) can embed the engine with it.", "",
           '!!! info "Design"', ""]
    out += ["    " + l if l else "" for l in capi["intro"].splitlines()]
    out.append("")
    for sec in capi["sections"]:
        out += [f"## {sec['title']}", "", "| Declaration | Notes |", "|---|---|"]
        for item in sec["items"]:
            if item["kind"] == "struct":
                continue
            out.append(f"| `{md_escape(item['decl'])}` | {md_escape(item['doc'])} |")
        out.append("")
        for item in sec["items"]:
            if item["kind"] == "struct":
                out += [md_escape(item["doc"]), "", "```c", *item["decl"].splitlines(), "```", ""]
    out += ["## Example", "", "```c",
            '#include "sky_api.h"',
            "",
            "int main(void) {",
            '    SkyEngine* engine = sky_engine_create("my_game");',
            '    char* result = sky_call_tool(engine, "entity_create",',
            '                                 "{\\"name\\": \\"Crate\\", \\"mesh\\": \\"cube\\", \\"position\\": [0, 0.5, 0]}",',
            '                                 "user");',
            "    sky_string_free(result);",
            "    sky_update(engine, 1.0 / 60.0);",
            "    sky_engine_destroy(engine);",
            "    return 0;",
            "}", "```", ""]
    return {"reference/capi.md": "\n".join(out)}


# ---------------------------------------------------------------------------------------------------------------
# Examples gallery


def scene_stats(project: Path) -> dict:
    kinds: Counter = Counter()
    entities = behaviors = 0
    env = {}
    scenes = []
    for f in sorted((project / "scenes").glob("*.sky.json")):
        if " 2." in f.name:  # iCloud duplicates
            continue
        scenes.append(f.relative_to(project).as_posix())
        try:
            doc = json.loads(f.read_text())
        except (OSError, json.JSONDecodeError):
            continue
        env = env or doc.get("environment", {})
        for e in doc.get("entities", []):
            entities += 1
            behaviors += len(e.get("behaviors", []))
            kinds.update(e.get("components", {}).keys())
    return {"scenes": scenes, "kinds": kinds, "entities": entities, "behaviors": behaviors, "env": env}


FEATURE_FROM_COMPONENT = OrderedDict([
    ("terrain", "Terrain"), ("foliage", "Foliage"), ("water", "FFT water"), ("fluid", "Fluid fire and smoke"),
    ("particles", "Particles"), ("groom", "Hair"), ("sprite", "Sprites"), ("tilemap", "Tilemaps"), ("light2d", "2D lights"),
    ("ui", "UI"), ("text", "World text"), ("dialogue", "Dialogue"), ("body", "Physics"), ("character", "Characters"),
    ("nav_agent", "Navigation"), ("animator", "Skeletal animation"), ("sequencer", "Sequences"), ("audio", "Audio"),
])


def gen_examples(curated: dict) -> dict[str, str]:
    projects = sorted(p for p in (ROOT / "examples").iterdir() if p.is_dir() and (p / "scenes").is_dir())
    unknown = [p.name for p in projects if p.name not in curated["projects"]]
    if unknown:
        raise SystemExit(f"examples without an entry in website/data/examples.json: {', '.join(unknown)}")
    order = list(curated["projects"])
    projects.sort(key=lambda p: order.index(p.name))
    cards, sections = [], []
    for p in projects:
        info = curated["projects"][p.name]
        game = {}
        if (p / "game.json").exists():
            game = json.loads((p / "game.json").read_text())
        title = game.get("title", info.get("title", p.name))
        genre = game.get("genre", info.get("genre", ""))
        pitch = game.get("pitch", info.get("pitch", ""))
        stats = scene_stats(p)
        auto = [label for comp, label in FEATURE_FROM_COMPONENT.items() if stats["kinds"].get(comp)]
        if stats["behaviors"]:
            auto.append("Wander")
        sky = stats["env"].get("skyMode")
        if sky in ("atmosphere", "hdri"):
            auto.append("HDRI sky" if sky == "hdri" else "Atmosphere")
        if stats["env"].get("cloudMode") == "volumetric" and stats["env"].get("clouds", 0) > 0:
            auto.append("Volumetric clouds")
        features = list(dict.fromkeys(info.get("features", []) + auto))
        image = info.get("image")
        media = (f'<img src="../assets/{image}" alt="{title}" loading="lazy">' if image else
                 '<div class="sky-placeholder"><strong>Render on first build</strong>'
                 'This project downloads its CC0 assets on first build</div>')
        tags = "".join(f'<span class="sky-tag">{f}</span>' for f in features[:6])
        cards.append(f'<a class="sky-card" href="#{p.name}">{media}<div class="sky-card__body">'
                     f'<p class="sky-card__title">{title}</p><p class="sky-card__meta">{genre}</p>'
                     f'<p class="sky-card__text">{pitch}</p><div class="sky-tags">{tags}</div></div></a>')
        sec = [f"## {title} {{ #{p.name} }}", ""]
        if info.get("video"):
            poster = f' poster="../assets/{image}"' if image else ""
            sec += [f'<video controls muted loop playsinline preload="none"{poster}>'
                    f'<source src="../assets/{info["video"]}" type="video/mp4"></video>', ""]
        elif image:
            sec += [f"![{title}](../assets/{image}){{ loading=lazy }}", ""]
        sec += [f"*{genre}* · {pitch}" if genre else pitch, "", info["description"].strip(), ""]
        sec += ["| | |", "|---|---|",
                f"| Folder | [`examples/{p.name}`]({REPO}examples/{p.name}) |",
                f"| Scenes | {', '.join(f'`{s}`' for s in stats['scenes'])} |",
                f"| Size | {stats['entities']} entities, {stats['behaviors']} behaviors |",
                f"| Demonstrates | {', '.join(features)} |"]
        if game.get("assets"):
            sec.append(f"| Assets | {md_escape(game['assets'])} |")
        if info.get("needs_download"):
            sec.append("| Note | Downloads its CC0 assets (models, textures, HDRI) on the first build; see the project's "
                       "`CREDITS.md` |")
        sec.append("")
        scene = stats["scenes"][0] if stats["scenes"] else "scenes/main.sky.json"
        sec += ['=== "Editor"', "", "    ```bash",
                f'    open build/release/bin/Skywalker.app --args --project "$PWD/examples/{p.name}"', "    ```", "",
                '=== "Render a still"', "", "    ```bash",
                f"    skywalker render examples/{p.name}/{scene} -o {p.name}.png --scene-camera --samples 8", "    ```", "",
                '=== "Play it"', "", "    ```bash", f"    skywalker-player examples/{p.name}", "    ```", "",
                '=== "Agent"', "", "    ```bash", f"    skywalker mcp --project examples/{p.name} --scene {scene}", "    ```", ""]
        sections.append("\n".join(sec))
    page = [BANNER, "# Examples", "",
            f"{len(projects)} sample projects ship in [`examples/`]({REPO}examples). Most were built by agent crews "
            "through the engine's own tools, and every one is original: its own world, characters and story. Open any of "
            "them in the editor, render it from the command line, play it in the standalone player, or point an agent at it.",
            "", '<div class="sky-grid">', *cards, "</div>", "", *sections]
    return {"examples/index.md": "\n".join(page)}


# ---------------------------------------------------------------------------------------------------------------


def generate() -> dict[str, str]:
    CURATED.clear()
    CURATED.update({k: v for k, v in load("tool_examples.json").items() if not k.startswith("_")})
    pages = {}
    pages.update(gen_tools(load("tools.json")))
    pages.update(gen_components(load("components.json")))
    pages.update(gen_wander(load("wander.json")))
    pages.update(gen_cli(load("cli.json")))
    pages.update(gen_capi(load("capi.json")))
    pages.update(gen_examples(load("examples.json")))
    out = {}
    for rel, text in pages.items():
        # Front matter gives the page its title (the banner comment would otherwise hide the first heading).
        m = re.match(re.escape(BANNER) + r"\n?# (.+)\n", text)
        if m:
            title = m.group(1).replace('"', "'")
            text = f'---\ntitle: "{title}"\n---\n' + text
        out[rel] = text.rstrip() + "\n"
    return out


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="fail if committed pages differ from what would be generated")
    ap.add_argument("--fresh", help="folder with a fresh dump_data.py output to compare website/data against")
    opts = ap.parse_args()
    problems = []
    if opts.fresh:
        for name in ("tools.json", "components.json", "wander.json", "cli.json", "capi.json"):
            fresh, committed = Path(opts.fresh) / name, DATA / name
            if not committed.exists() or fresh.read_text() != committed.read_text():
                problems.append(f"website/data/{name} is stale (the engine changed)")
    pages = generate()
    if opts.check:
        for rel, text in pages.items():
            path = DOCS / rel
            if not path.exists() or path.read_text() != text:
                problems.append(f"website/docs/{rel} is stale")
        generated = {DOCS / rel for rel in pages}
        for path in list((DOCS / "reference").rglob("*.md")):
            if BANNER in path.read_text()[:400] and path not in generated:
                problems.append(f"website/docs/{path.relative_to(DOCS)} is no longer generated: delete it")
        for p in problems:
            print(p)
        if problems:
            print("regenerate: python3 website/scripts/dump_data.py --cli build/<preset>/bin/skywalker && "
                  "python3 website/scripts/gen_reference.py", file=sys.stderr)
            return 1
        print(f"reference pages up to date ({len(pages)} pages)")
        return 0
    for p in problems:
        print(p)
    for rel, text in pages.items():
        path = DOCS / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        if not path.exists() or path.read_text() != text:
            path.write_text(text)
    print(f"wrote {len(pages)} pages")
    return 0


if __name__ == "__main__":
    sys.exit(main())
