"""Generates typed tool wrappers (``_generated.py``) from ``skywalker tools --json``.

Each engine tool becomes a pydantic argument model and a method on :class:`AsyncTools` and
:class:`Tools`, so ``await engine.tools.viewport_capture(width=640, annotate=True)`` is checked
by your type checker and validated before it reaches the engine. Regenerate after engine tool
changes with ``sky-agents gen-tools``.
"""

from __future__ import annotations

import json
import keyword
import re
import subprocess
from typing import Any

HEADER = '''"""Typed wrappers for every engine tool.

GENERATED by ``sky-agents gen-tools`` from ``skywalker tools --json``.

Do not edit by hand: regenerate after changing engine tools.
Engine version: {version}. {count} tools.
"""
# ruff: noqa
# fmt: off
from __future__ import annotations

from typing import TYPE_CHECKING, Any, Literal, Protocol

from pydantic import BaseModel, ConfigDict, Field

from .results import ToolResult


class _AsyncCaller(Protocol):
    async def call(self, tool: str, args: dict[str, Any] | None = None, /, *, check: bool = False,
                   timeout: float | None = None) -> ToolResult: ...


class _SyncCaller(Protocol):
    def call(self, tool: str, args: dict[str, Any] | None = None, /, *, check: bool = False,
             timeout: float | None = None) -> ToolResult: ...


class _Args(BaseModel):
    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    def to_args(self) -> dict[str, Any]:
        return self.model_dump(by_alias=True, exclude_none=True)


def _args(model: type[_Args], values: dict[str, Any]) -> dict[str, Any]:
    clean = {{k: v for k, v in values.items() if v is not None}}
    return model.model_validate(clean).to_args()

'''


def _pascal(name: str) -> str:
    return "".join(p.capitalize() for p in re.split(r"[_\-]+", name) if p) + "Args"


def _ident(name: str) -> str:
    ident = re.sub(r"\W", "_", name)
    if keyword.iskeyword(ident) or ident in ("self", "check", "timeout", "model_config"):
        ident += "_"
    if ident[0].isdigit():
        ident = "_" + ident
    return ident


def py_type(schema: Any) -> str:
    """A Python annotation for a JSON Schema fragment (lenient: unknowns become Any)."""
    if not isinstance(schema, dict):
        return "Any"
    if "enum" in schema and isinstance(schema["enum"], list) and schema["enum"]:
        values = ", ".join(repr(v) for v in schema["enum"])
        return f"Literal[{values}]"
    t = schema.get("type")
    if isinstance(t, list):
        parts = [py_type({**schema, "type": x}) for x in t if x != "null"]
        uniq = list(dict.fromkeys(parts))
        return " | ".join(uniq) if uniq else "Any"
    if t == "string":
        return "str"
    if t == "integer":
        return "int"
    if t == "number":
        return "float"
    if t == "boolean":
        return "bool"
    if t == "array":
        return f"list[{py_type(schema.get('items'))}]"
    if t == "object":
        return "dict[str, Any]"
    for key in ("anyOf", "oneOf"):
        if isinstance(schema.get(key), list):
            parts = list(dict.fromkeys(py_type(x) for x in schema[key]))
            return " | ".join(parts) if parts else "Any"
    return "Any"


def _doc(text: str, indent: str) -> str:
    text = text.replace("\\", "\\\\").replace('"""', '\\"\\"\\"').strip()
    lines = text.splitlines() or [""]
    body = "\n".join(indent + ln if ln else "" for ln in lines[1:])
    first = lines[0]
    return f'{indent}"""{first}' + (f"\n{body}\n{indent}" if body else "") + '"""\n'


def generate(tools: list[dict[str, Any]], version: str = "") -> str:
    tools = sorted(tools, key=lambda t: t["name"])
    out = [HEADER.format(version=version or "unknown", count=len(tools))]
    methods_async: list[str] = []
    methods_sync: list[str] = []
    for t in tools:
        name = t["name"]
        schema = t.get("inputSchema") or {}
        props: dict[str, Any] = schema.get("properties") or {}
        required = set(schema.get("required") or [])
        model = _pascal(name)
        fields = []
        params = []
        for pname, pschema in props.items():
            ident = _ident(pname)
            ann = py_type(pschema)
            desc = str((pschema or {}).get("description", "")) if isinstance(pschema, dict) else ""
            alias = f", alias={pname!r}" if ident != pname else ""
            if pname in required:
                fields.append(f"    {ident}: {ann} = Field(...{alias}, description={desc!r})\n")
                params.append((0, f"{ident}: {ann}"))
            else:
                fields.append(f"    {ident}: {ann} | None = Field(None{alias}, description={desc!r})\n")
                params.append((1, f"{ident}: {ann} | None = None"))
        out.append(f"class {model}(_Args):\n")
        out.append(_doc(f"Arguments of `{name}`.", "    "))
        out.extend(fields or ["    pass\n"])
        out.append("\n\n")
        params.sort(key=lambda p: p[0])
        sig = ", ".join(["self", "*", *[p[1] for p in params], "check: bool = False", "timeout: float | None = None"])
        values = ", ".join(f"{p!r}: {_ident(p)}" for p in props)
        doc = _doc(str(t.get("description", "")), "        ")
        call_expr = f"self._c.call({name!r}, _args({model}, {{{values}}}), check=check, timeout=timeout)"
        methods_async.append(
            f"    async def {_ident(name)}({sig}) -> ToolResult:\n{doc}        return await {call_expr}\n\n"
        )
        methods_sync.append(f"    def {_ident(name)}({sig}) -> ToolResult:\n{doc}        return {call_expr}\n\n")
    out.append("class AsyncTools:\n")
    out.append(_doc("Every engine tool as a typed async method (``await engine.tools.<name>(...)``).", "    "))
    out.append("\n    def __init__(self, caller: _AsyncCaller) -> None:\n        self._c = caller\n\n")
    out.extend(methods_async)
    out.append("\nclass Tools:\n")
    out.append(_doc("Every engine tool as a typed method (``engine.tools.<name>(...)``).", "    "))
    out.append("\n    def __init__(self, caller: _SyncCaller) -> None:\n        self._c = caller\n\n")
    out.extend(methods_sync)
    out.append(f"\nTOOL_NAMES: tuple[str, ...] = {tuple(t['name'] for t in tools)!r}\n")
    return "".join(out)


def tools_from_binary(binary: str) -> tuple[list[dict[str, Any]], str]:
    raw = subprocess.run([binary, "tools", "--json"], check=True, capture_output=True, text=True).stdout
    version = subprocess.run([binary, "version"], check=False, capture_output=True, text=True).stdout.strip()
    return list(json.loads(raw)["tools"]), version.replace("skywalker ", "")
